Repository NicoleKoran/SOEN-341-Communications-Platform, pull requests merged in 2025-03, with the labels that each got.

#62 Added the following Features:
  backend/chats.json
  backend/database.json
  backend/server.js
  frontend/index.html
  frontend/script.js
  frontend/styles.css
Labels: enhancement, User Story

#69 Added login feature
  backend/server.js
  backend/users.json
  frontend/index.html
  frontend/login.css
  frontend/login.html
  frontend/login.js
  frontend/script.js
  frontend/styles.css
Labels: enhancement

#71 #66 fixed text alignment
  backend/chats.json
  backend/database.json
  frontend/styles.css
Labels: bug, enhancement

#75 Added Profile Picture Feature
  backend/chats.json
  backend/database.json
  backend/server.js
  backend/users.json
  frontend/default-avatar.png
  frontend/index.html
  frontend/script.js
  frontend/styles.css
Labels: enhancement

#77 added user role feature for admin along user delete feature
  backend/chats.json
  backend/database.json
  backend/server.js
  backend/uploads/RobertTest-1743179774144.png
  backend/users.json
  frontend/script.js
  frontend/styles.css
Labels: enhancement, Epic
